from Tool.asm_blocks import AsmUnit

# This Class is used to log the assembly code generated by the compiler
class AsmLogger:

    @staticmethod
    def print_asm_line(asm_code:str, comment:str=None):
        asm_unit = AsmUnit(asm_string=asm_code, comment=comment)
        print(asm_unit)

    @staticmethod
    def print_comment_line(comment: str, add_print:bool = False):
        asm_unit = AsmUnit(comment=comment)
        print(asm_unit)
