from Tool.asm_blocks import AsmUnit
from state_management import get_state_manager

# This Class is used to log the assembly code generated by the compiler
class AsmLogger:

    @staticmethod
    def print_asm_line(asm_code:str, comment:str=None):
        state_meneger = get_state_manager()
        asm_unit = AsmUnit(asm_string=asm_code, comment=comment)
        current_state = state_meneger.get_active_state()
        current_code_block = current_state.current_code_block
        current_code_block.asm_units_list.append(asm_unit)
        print(asm_unit)

    @staticmethod
    def print_comment_line(comment: str, add_print:bool = False):
        state_meneger = get_state_manager()
        asm_unit = AsmUnit(comment=comment)
        current_state = state_meneger.get_active_state()
        current_code_block = current_state.current_code_block
        current_code_block.asm_units_list.append(asm_unit)
        print(asm_unit)
