name: Run Airtable Tool

on:
  workflow_dispatch: # Allows you to manually trigger the workflow from GitHub
  push:
    branches:
      - main           # Runs the workflow whenever code is pushed to the main branch


jobs:
  run-tool:
    runs-on: ubuntu-latest  # The environment in which the tool runs (Linux in this case)

    steps:
    - name: Check out repository
      uses: actions/checkout@v3  # Fetches your code from the repository

    - name: Set up Python
      uses: actions/setup-python@v4  # Installs Python
      with:
        python-version: '3.12'        # Specify the version of Python your tool requires

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Installs dependencies from requirements.txt

    - name: Run Airtable Tool
      env:
        AIRTABLE_PAT: ${{ secrets.ARROW_AIRTABLE_RUN_STATISTICS_UPLOAD_TOKEN }}  # Securely passes the token to the script
      run: |
        python Arrow/main.py  # Runs your tool
