name: Verify Airtable Secret

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  check-secret:
    runs-on: ubuntu-latest  # Use the default Ubuntu runner

    steps:
    - name: Print Environment Variables
      run: printenv  # Print all environment variables for debugging

    - name: Verify Airtable Token
      run: |
        if [ -z "$AIRTABLE_PAT" ]; then
          echo "AIRTABLE_PAT is not set"
          exit 1
        else
          echo "AIRTABLE_PAT is set"
        fi
      env:
        AIRTABLE_PAT: ${{ secrets.ARROW_AIRTABLE_RUN_STATISTICS_UPLOAD_TOKEN }}  # Inject the secret
